# Measure Theory {#ch1}

## Preliminaries

The **open ball** in $\mathbb{R}^d$ centered at $x$ and of radius $r$ is defined by
$$
B_r(x)=\{y\in \mathbb{R}^d :|y−x|<r\}.
$$
A subset $E\subset\mathbb{R}^d$ is **open** if for every $x\in E$ there exists $r>0$ with $B_r(x)\subset E$. By definition, a set is **closed** if its complement is open.


We note that any (not necessarily countable) union of open sets is open, while in general the intersection of only finitely many open sets is open. A similar statement holds for the class of closed sets, if one interchanges the roles of unions and intersections.

A set $E$ is **bounded** if it is contained in some ball of finite radius. A bounded set is **compact** if it is also closed. Compact sets enjoy the **Heine-Borel covering property**:

- Assume $E$ is compact, $E\subset \bigcup_{\alpha}\cal{O}_{\alpha}$, and each $\cal{O}_{\alpha}$ is open. Then there are finitely many of the open sets, $\cal{O}_{\alpha_1},{O}_{\alpha_2},\dots,{O}_{\alpha_N}$, such that $E\subset \bigcup_{j=1}^n\cal{O}_{\alpha_j}$.

In words, any covering of a compact set by a collection of open sets contains a finite subcovering.

A point $x\in \mathbb{R}^d$ is a **limit point** of the set $E$ if for every $r>0$,the ball $B_r(x)$ contains points of $E$. This means that there are points in $E$ which are arbitrarily close to $x$. An **isolated point** of $E$ is a point $x\in E$ such that there exists an $r > 0$ where $B_r(x)\cap E$ is equal to $\{x\}$.

A point $x\in E$ is an **interior point** of $E$ if there exists $r>0$ such that $B_r(x)\subset E$. The set of all interior points of E is called the **interior** of $E$. Also, the **closure** $\overline{E}$ of the $E$ consists of the union of $E$ and all its *limit points*. The **boundary** of a set $E$, denoted by $\partial E$, is the set of points which are in the closure of $E$ but not in the interior of $E$.

Note that the closure of a set is a closed set; every point in $E$ is a limit point of $E$; and a set is closed if and only if it contains all its limit points. Finally, a closed set $E$ is **perfect** if $E$ does not have any isolated points.

:::{.lemma}
If a rectangle is the almost disjoint union of finitely many other rectangles, say $R=\bigcup_{k=1}^NR_k$, then
$$
|R|=\sum_{k=1}^N |R_k|
$$
:::

:::{.lemma}
If $R,R_1,\dots,R_N$ are rectangles, and $R\subset\bigcup_{k=1}^NR_k$, then
$$
|R|\leq\sum_{k=1}^N |R_k|
$$
:::
<details>
  <summary>*Proof.*</summary>
</details>


:::{.Theorem}
Every open subset $\cal{O}$ of $\mathbb{R}$ can be written uniquely as a countable union of disjoint open intervals.
:::

:::{.Theorem}
Every open subset $\cal{O}$ of $\mathbb{R}^d$, $d\geq 1$, can be written uniquely as a countable union of almost disjoint closed cubes.
:::

The **Cantor set** $\cal{C}$ is by definition the intersection of all $C_k$’s:
$$
\mathcal{C}=\bigcap_{k=0}^{\infty}C_k.
$$

The set $\cal{C}$ is not empty, since all end-points of the intervals in $C_k$ (all $k$) belong to $\cal{C}$.
Despite its simple construction, the Cantor set enjoys many interesting topological and analytical properties. For instance, $\cal{C}$ is closed and bounded, hence compact. Also, $\cal{C}$ is totally disconnected: given any $x,y\in \cal{C}$ there exists $z\not\in \cal{C}$ that lies between $x$ and $y$. Finally, $\cal{C}$ is perfect: it has no isolated points.

In terms of cardinality the Cantor set is rather large: it is not countable. Since it can be mapped to the interval $[0,1]$, the Cantor set has the cardinality of the continuum. However, from the point view of "length" the size f $\cal C$ is small. Roughly speaking, it has length zero.

## The exterior measure

:::{.definition}
If $E$ is any subset of $\mathbb{R}^d$, the **exterior measure** of $E$ is
$$
m_{\ast}(E) = \inf\sum_{j=1}^{\infty}|Q_j|,
$$
where the infimum is taken over all countable coverings $E\subset \bigcup_{j=1}^{\infty}Q_j$ by closed cubes. In general we have $0\leq m_{\ast}(E)\leq \infty$.
:::

- It would not suffice to allow finite sums in the definition of $m_{\ast}(E)$. The quantity that would be obtained if one considered only coverings of $E$ by finite unions of cubes is in general larger than $m_{\ast}(E)$.
- One can, however, replace the coverings by cubes, with coverings by rectangles; or with coverings by balls.

:::{.example}
The exterior measure of a closed cube is equal to its volume.
:::
<details>
  <summary>*Proof.*</summary>
  We consider an arbitrary covering $Q\subset \bigcup_{j=1}^{\infty}Q_j$ by cubes, where $Q_j$ is closed for $j=1,2,\dots$. Then it suffices to prove that 
  $$
  |Q|\leq \sum_{j=1}^{\infty}|Q_j|.
  $$
</details>

:::{.example}
The exterior measure of a open cube is equal to its volume.
:::

:::{.example}
The exterior measure of a rectangle is equal to its volume.
:::
<details>
  <summary>*Proof.*</summary>
  Arguing as in the first example, we see that $|R|\leq m_{\ast}(R)$. To obtain the reverse inequality, consider a grid in $\mathbb{R}^d$ formed by cubes of side length $1/k$, then let $k$ tend to infinity yields $m_{\ast}(R)\leq |R|$.
</details>

:::{.example}
The Cantor set $\cal C$ has exterior measure 0.
:::

### Properties of the exterior measure

From the definition we know that:
- For every $\epsilon>0$, there exists a covering $E\subset \bigcup_{j=1}^{\infty}Q_j$ with
$$
\sum_{j=1}^{\infty}m_{\ast}(Q_j)\leq m_{\ast}(E)+\epsilon.
$$

:::{.proposition #pem}
1. (Monotonicity) If $E_1\subset E_2$, then $m_{\ast}(E_1)\leq m_{\ast}(E_2)$.
2. (Countatble sub-additivity) If $E= \bigcup_{j=1}^{\infty}E_j$, then $m_{\ast}(E)\leq\sum_{j=1}^{\infty}m_{\ast}(E_j)$.
3. If $E\subset\mathbb{R}^d$, then $m_{\ast}(E)=\inf m_{\ast}(\cal O)$, where the infimum is taken over all open sets $\cal O$ containing $E$.
<details>
  <summary>*Proof.*</summary>
  It suffices to prove that $m_{\ast}(E)\geq \inf m_{\ast}(\cal O)$. Notice that for any closed cube $Q_j$, there exists an open set $S_j$ which contains $Q_j$ and such that $|S_j|\leq (1+\epsilon)|Q_j|$ for a fixed $\epsilon>0$.
</details>
4. If $E=E_1\cup E_2$,and $d(E_1,E_2)>0$, then
$$
 m_{\ast}(E)=  m_{\ast}(E_1)+  m_{\ast}(E_2).
$$
5. If a set $E$ is the countable union of almost disjoint cubes $E=\bigcup_{j=1}^{\infty}Q_j$, then
$$
m_{\ast}(E) = \sum_{j=1}^{\infty}|Q_j|.
$$
<details>
  <summary>*Proof.*</summary>
  Consider constructing a family of cubes that are at a finite distance from one another, so we can use proposition 4.
</details>
:::

## Measurable sets and the Lebesgue measure
The notion of measurability isolates a collection of subsets in $\mathbb{R}^d$ for which the exterior measure satisfies all our desired properties, including additivity (and in fact countable additivity) for disjoint unions of sets.

There are a number of different ways of defining measurability, but these all turn out to be equivalent. Probably the simplest and most intuitive is the following: A subset $E$ of $\mathbb{R}^d$ is **Lebesgue measurable**, or simply **measurable**, if for any $\epsilon > 0$ there exists an open set $\cal O$ with $E\subset\cal O$ and
$$
m_{\ast}(\mathcal{O}-E) ≤ \epsilon.
$$
This should be compared to Proposition \@ref(prp:pem) 3, which holds for all sets $E$. If E is measurable, we define its **Lebesgue measure** (or **measure**) $m(E)$ by
$$
m(E)=m_{\ast}(E).
$$

Immediately from the definition, we find:

:::{.proposition}
1. Every open set in $\mathbb{R}^d$ is measurable.
2. If $m_{\ast}(E)=0$, then $E$ is measurable. In particular, if $F$ is a subset of a set of exterior measure $0$, then $F$ is measurable.
3. A countable union of measurable sets is measurable.
4. Closed sets are measurable.
<details>
  <summary>*Proof.*</summary>
  Since any closed set $F$ can be written as the union of compact sets, say $F=\bigcup_{k=1}^{\infty}F\cap B_k$, where $B_k$ denotes the closed ball of radius $k$ centered at the origin, it suffices to prove that compact sets are measurable.
</details>
5. The complement of a measurable set is measurable.
<details>
  <summary>*Proof.*</summary>
  For every positive integer $n$ we choose an open set $\cal O_n$ with $E\subset \cal O_n$ and $m_{\ast}(\mathcal{O_n}-E)\leq 1/n$. Notice that
  $$
  (E^c-\bigcup_{n=1}^{\infty}\mathcal{O_n^c}) \subset(\mathcal{O_n}-E)
  $$
  then $E^c$ is measurable since $E^c=(E^c-\bigcup_{n=1}^{\infty}\mathcal{O_n^c})\cup \bigcup_{n=1}^{\infty}\mathcal{O_n^c}$.
</details>
6. A countable intersection of measurable sets is measurable.
:::

To prove the fourth proposition, we need the following lemma.

:::{.lemma}
If $F$ is closed, $K$ is compact, and these sets are disjoint, then $d(F,K)>0$.
:::

:::{.theorem}
If $E_1,E_2,\dots$, are disjoint measurable sets, and $E=\bigcup_{j=1}^{\infty}E_j$, then
$$
m(E)=\sum_{j=1}^{\infty}m(E_j).
$$
:::
<details>
  <summary>*Proof.*</summary>
  If $F_1,F_2,\dots, F_N$, are compact and disjoint, then obviously for any $j,k,j\ne k$, $d(F_j,F_k)>0$, so $m\left(\bigcup_{j=1}^NF_j\right)=\sum_{j=1}^Nm(F_j)$. If each $E_j$ is bounded, we can choose a closed subset $F_j$ for $E_j$ with $m_{\ast}(E_j-F_j)\leq \epsilon/2^j$ for each $j$. Then
  $$
  m(E) \geq \sum_{j=1}^Nm(F_j) \ge \sum_{j=1}^Nm(E_j)-\epsilon
  $$
  Letting $N$ tend to infinity, since $\epsilon$ is arbitrary we find that 
  $$
  m(E)\ge\sum_{j=1}^{\infty}m(E_j).
  $$
  In the general case, we select any sequence of cubes $\{Q_k\}_{k=1}^{\infty}$ that increases to $\mathbb{R}^d$, in the sense that $Q_k\subset Q_{k+1}$ for all $k\ge 1$ and $\bigcup_{k=1}^{\infty}Q_k=\mathbb{R}^d$. We then let $S_1=Q_1$ and $S_k=Q_k-Q_{k-1}$ for $k\ge 2$. If we define measurable sets by $E_{j,k}=E_j\cap S_k$, then
  $$
  m(E) =\sum_{j,k}m(E_{j,k})=\sum_j\sum_km(E_{j,k})=\sum_jm(E_j).
  $$
</details>

:::{.corollary}
Suppose $E_1,E_2,...$ are measurable subsets of $\mathbb{R}^d$.

- If $E_k \nearrow E$, then $m(E) =\lim_{N\to \infty}m(E_N)$.
- If $E_k \searrow E$ and $m(E_k)<\infty$ for some $k$, then $m(E) =\lim_{N\to \infty}m(E_N)$.
:::

:::{.theorem #m}
Suppose $E$ is measurable subset of $\mathbb{R}^d$. Then for every $\epsilon>0$:

1. There exists an open set $\cal O$ with $E\subset \cal O$ and $m(\mathcal{O}-E)\leq\epsilon$. 
2. There exists a closed set $F$ with $F\subset E$ and $m(E-F)\leq\epsilon$. 
3. If $m(E)$ is finite, there exists a compact set $K$ with $K\subset E$ and $m(E-K)\leq \epsilon$.
4. If $m(E)$ is finite, there exists a finite union $F=\bigcup_{j=1}^NQ_j$ of closed cubes such that
$$
m(E\triangle F)\leq \epsilon.
$$
<details>
  <summary>*Proof.*</summary>
  Choose a family of closed cubes $\{Q_j\}_{j=1}^{\infty}$ so that
  $$
  E\subset \bigcup_{j=1}^{\infty}Q_j \text{ and } \sum_{j=1}^{\infty}|Q_j|\le m(E) +\epsilon/2.
  $$
 Since $m(E) <\infty$, then series converges and there exists $N>0$ such that $\sum_{j=n+1}^{\infty}|Q_j|\le \epsilon/2$. If $F=\bigcup_{j=1}^NQ_j$, then
 $$
 \begin{aligned}
 m(E\triangle F) &= m(E-F)+m(F-E)\\
 &\le m\left( \bigcup_{j=1}^{\infty}Q_j - F\right)+m\left( \bigcup_{j=1}^{\infty}Q_j-E\right)\\
 &\le m\left( \bigcup_{j=n+1}^{\infty}Q_j\right)+ m\left( \bigcup_{j=n+1}^{\infty}Q_j\right)-m(E)\\
 &\le \sum_{j=n+1}^{\infty}|Q_j|+\sum_{j=1}^{\infty}|Q_j|-m(E)\\
 &\le \epsilon.
 \end{aligned}
 $$
</details>
:::

### Invariance properties of Lebesgue measure

### $\sigma$-algebra and Borel sets
**Borel $\sigma$-algebra** in $\mathbb{R}^d$, denoted by $\cal B_{\mathbb{R}^d}$, is the smallest $\sigma$-algebra in $\mathbb{R}^d$ that contains all open sets. Elements of this $\sigma$-algebra are called **Borel sets**. Since we observe that any intersection (not necessarily countable) of $\sigma$-algebra is again a $\sigma$-algebra, we may define $\cal B_{\mathbb{R}^d}$ as the intersection of all $\sigma$-algebras that contain the open sets. This shows the existence and uniqueness of the Borel $\sigma$-algebra.

:::{.remark}
There exists Lebesgue measurable sets that are not Borel sets. (See Exercise \@ref(exr: #35)
:::

### Construction of a non-measurable set

### Axiom of choice

## Measurable functions

### Definition and basic properties

The starting point is the notion of a **characteristic function** of a set E, which is defined by
$$
\chi_E(x)=
\begin{cases}
1& \text{if }x\in E,\\
0& \text{if }x\not\in E.
\end{cases}
$$
For the Riemann integral it is in effect theclass of **step functions** that build the blocks of integration theory , with each give as a finite sum

$$
f = \sum_{k=1}^Na_k\chi_{R_k}
$$
where each $R_k$ is a rectangle, and the $a_k$ are constants.

For the lebesgue integral we need a more general notion. A **simple function** is a finite sum
$$
f = \sum_{k=1}^Na_k\chi_{E_k}
$$
where each $E_k$ is a measurable set of finite measure, and the $a_k$ are constants.

A function $f$ defined on a measurable subset $E$ of $\mathbb{R}^d$ is **measurable**, if for all $a\in\mathbb{R}$, the set
$$
f^{-1}([-\infty,a))=\{x\in E: f(x)<a\}
$$
is measurable. Note that this definition applies to extended-valued functions, so we use $f^{-1}([-\infty,a))$ instead of $f^{-1}((-\infty,a))$.

:::{.proposition}
1. The finite-valued function $f$ is measurable iff $f^{-1}(\cal O)$ is measurable for every open set $\cal O$, and iff $f^{-1}(F)$ is measurable for every closed set $F$. (Note that this property also applies to extended-valued functions, if we make the additional hypothesis that both $f^{-1}(\infty)$ and $f^{-1}(-\infty)$ are measurable sets since $[-\infty,a)=\{-\infty\}\cup\left(\bigcup_{n=1}^{\infty}(-n,a)\right)$.)
2. If $f$ is continuous on $\mathbb{R}^d$, then $f$ is measurable. If $f$ is measurable and finite-valued, and $\Phi$ is continuous, then $\Phi\circ f$ is measurable. (Note that it is not true that $f\circ\Phi$ is measurable. See exercise 35.)
<details>
<summary>*Proof.*</summary>
$\Phi$ is continuous, so $\Phi^{-1}((-\infty,a))$ is open set $\cal O$.
</details>
3. Suppose $\{f_n\}_{n=1}^{\infty}$ is a sequence of measurable functions. Then
$$
\sup_nf_n(x),\quad \inf_nf_n(x),\quad\limsup_{n\to\infty}f_n(x)\quad \text{and} \quad\liminf_{n\to\infty}f_n(x)
$$
are measurable.
4. If $\{f_n\}_{n=1}^{\infty}$ is a collection of measurable functions, and
$$
\lim_{n\to\infty}f_n(x)=f(x),
$$
then $f$ is measurable.
5. If $f$ and $g$ are measurable, then
(i) The integer powers $f^k$, $k\ge 1$ are measurable.
(ii) $f+g$ and $fg$ are measurable if both $f$ and $g$ are finite-valued.
6. Suppose $f$ is measurable, and $f(x)=g(x)$ for a.e. $x$. Then $g$ is measurable.
:::

### Approximation by simple functions or step functions

:::{.theorem}
Suppose $f$ is a non-negative measurable function on $\mathbb{R}^d$. Then there exists an increasing sequence of non-negative simple functions $\{\varphi_n\}_{n=1}^{\infty}$ that converges pointwise to $f$, namely,
$$
\varphi_k(x)\le\varphi_{k+1}(x) \text{ and } \lim_{k\to \infty}\varphi_k(x)=f(x),\ \text{for all }x.
$$
<details>
<summary>*Proof.*</summary>
$\Phi$ is continuous, so $\Phi^{-1}((-\infty,a))$ is open set $\cal O$.
</details>
:::

:::{.theorem #s}
Suppose $f$ is a measurable function on $\mathbb{R}^d$. Then there exists a sequence of simple functions $\{\varphi_n\}_{n=1}^{\infty}$ that satisfies
$$
|\varphi_k(x)|\le|\varphi_{k+1}(x)| \text{ and } \lim_{k\to \infty}\varphi_k(x)=f(x),\ \text{for all }x.
$$
<details>
<summary>*Proof.*</summary>
We use the decomposition of $f$: $f(x)=f^{+}(x)-f^{-}(x)$.
</details>
:::

:::{.theorem}
Suppose $f$ is measurable on $\mathbb{R}^d$. Then there exists an sequence of step functions $\{\psi_n\}_{n=1}^{\infty}$ that converges pointwise to $f(x)$ for almost every $x$,
$$
\varphi_k(x)\le\varphi_{k+1}(x) \text{ and } \lim_{k\to \infty}\varphi_k(x)=f(x),\ \text{for all }x.
$$
<details>
<summary>*Proof.*</summary>
By Theorem \@ref(thm:s), it suffices to show that if $E$ is a measurable set with finite measure, then $f=\chi_E$ can be approximated by step functions. This can be proven by split $E$ into cubes and then rectangles with Theorem \@ref(thm:m).
</details>
:::

### Littlewood's three principles

:::{.theorem #egorov name="Egorov"}
Suppose $\{f_k\}_{k=1}^{\infty}$ is a sequence of measurable functions defined on a measurable set $E$ with $m(E)<\infty$, and assume that $f_k\to f$ a.e. on $E$ and $f_1,f_2,\dots,f_k,f$ are finite valued a.e. on $E$. Given $\epsilon>0$, we can find a closed set $A_{\epsilon}\subset E$ such that $m(E-A_{\epsilon})\le \epsilon$ and $f_k\to f$ uniformly on $A_{\epsilon}$.
:::

:::{.remark}
Note that $f_1,f_2,\dots,f_k,f$ are finite valued a.e. on $E$. Indeed, if it is not satisfied, then we cannot construct $\{E_k^n\}_{k=1}^\infty$ such that $E_k^n\nearrow E$. A counterexample is that 
$$
f_k(x)=\begin{cases}
k&|x|\le k,\\
\infty &|x|>k
\end{cases}
$$
and $f(x)=\infty$ on $\mathbb{R}$.
:::

:::{.remark}
Note that $m(E)<\infty$ and it is easy to construct counterexamples when $m(E)=\infty$. Indeed, if $m(E)=\infty$, then we cannot find $k_n$ such that $m(E-E_{k_n}^n)<1/2^n$ since $m(E-E_{k_n}^n)=m(E)-m(E_{k_n}^n)$.
:::

:::{.theorem #lusin name="Lusin"}
Suppose $f$ is measurable and finite valued a.e. on $E$ with $E$ of finite measure. Then for every $\epsilon>0$ there exists a closed set $F_{\epsilon}$, with
$$
F_{\epsilon}\subset E, \text{ and }m(E-F_{\epsilon})\le \epsilon
$$
and such that $f|_{F_{\epsilon}}$ is continuous.
:::

## The Brunn-Minkowski inequality

:::{.remark}
Let $a,b\ge0$, then
$$
\begin{aligned}
(a+b)^\gamma&\ge a^\gamma+b^\gamma\text{ if }\gamma\ge 1,\\
(a+b)^\gamma&\le a^\gamma+b^\gamma\text{ if }0<\gamma< 1
\end{aligned}
$$
<details>
<summary>*Proof.*</summary>
Let $f(\gamma)=(1+x)^\gamma-(1+x^\gamma)$, where $x> 0$. Then 
$$
\begin{aligned}
f^\prime (\gamma)&=(1+x)^\gamma\ln(1+x)-x^\gamma\ln x\\
&=[(1+x)^\gamma-x^\gamma]\ln(1+x)+x^\gamma\ln(1+1/x)>0,
\end{aligned}
$$
notice that $f(1)=0$, so when $\gamma\ge 1$, $(1+x)^\gamma\ge(1+x^\gamma)$ and when $0<\gamma< 1$, $(1+x)^\gamma<(1+x^\gamma)$. With this result, the original inequality is obvious.
</details>
:::

\@ref(exr:19)

:::{.theorem}
Suppose $A$ and $B$ are measurable sets in $\mathbb{R}^d$ and their sum $A+B$ is also measurable. Then
$$
m(A+B)^{1/d}\ge m(A)^{1/d}+m(B)^{1/d}.
$$
:::

## Exercise

## Problem
