# Integration Theory {#ch2}

## The lebesgue integral: basic properties and convergence theorems

### Stage one: simple functions

:::{.proposition}
The integral of simpe functions defined bve satifies the following properties:

1. Independence of the representation. If $\varphi=\sum_{k=1}^Na_k\chi_{E_k}$ is any representation of $\varphi$, then
$$
\int \varphi=\sum_{k=1}^Na_km(E_k).
$$
2. Linearity.
3. Additivity. 
4. Monotonicity.
5. Triangle inequality. If $\varphi$ is a simple function, then so is $|\varphi|$, and
$$
\left|\int\varphi\right|\le \int|\varphi|.
$$
:::

### Stage two: bounded functions supported on a set of finite measure

:::{.lemma #l}
Let $f$ be a bounded function supported on a set $E$ of finite measure. If $\{\varphi_n\}_{n=1}^\infty$ is any sequence of simple functions bounded by $M$, supported on $E$, and with $\varphi_n(x)\to f(x)$ for a.e. $x$, then:

1. The limit $\lim_{n\to\infty}\int\varphi_n$ exists.
2. If $f=0$ a.e., then the limit $\lim_{n\to\infty}\int\varphi_n$ equals 0.
:::
<details>
<summary>*Proof.*</summary>
Setting $I_n=\int\varphi_n$ and applying Egorov's theorem which is proven in Chapter \@ref(ch1) we have that for and large $n$ and $m$
$$
\begin{aligned}
|I_n-I_m| &\le \int_E|\varphi_n-\varphi_m|\\
&=\int_{A_\epsilon}|\varphi_n-\varphi_m|+\int_{E-A_\epsilon}|\varphi_n-\varphi_m|\\
&\le \int_{A_\epsilon}\epsilon\ dx+\int_{E-A_\epsilon}2M\ dx\\
&\le m(E)\epsilon+2M\epsilon.
\end{aligned}
$$
given any $\epsilon>0$.
This proves that $\{I_n\}$ os a Cauchy sequence nd hence converges. If $f=0$, letting $m$ tend to infinity we have $|I_n-f|=|I_n|\le m(E)\epsilon+2M\epsilon$, which yields $\lim_{n\to\infty}I_n=0$.
</details>

For a bounded function $f$ that is supported on sets of finite measure, we define its **Lebesgue integral** by
$$
\int f=\lim_{n\to\infty}\int\varphi_n.
$$
where $\{\varphi_n\}$ is any sequence of simple functions satisfying: $|\varphi_n|\le M$, each $\varphi_n$ is supported on the support of $f$, and $\varphi_n(x)\to f(x)$ for a.e. $x$ as $n$ tends to infinity.

Next, we must show that $\int f$ is independent of the limiting sequence $\{\varphi_n\}$ used, in order for the integral to be well-defined. Suppose that $\{\psi_n\}$ is another sequence of simple functions that satisfies the properties above. Then, if $\eta_n = \varphi_n- \psi_n$, the sequence $\{\eta_n\}$ consists of simple functions bounded by $2M$, supported on a set of finite measure, and such that $\eta_n\to 0$ a.e. as $n$ tends to infinity. Applying the lemma we find
$$
\lim_{n\to\infty}\int \varphi_n =\lim_{n\to\infty}\int \psi_n+\lim_{n\to\infty}\int \eta_n=\lim_{n\to\infty}\int \psi_n
$$
as desired.

:::{.proposition}
Suppose $f$ and $g$ are bounded functions supported on sets of finite measure. Then the following properties hold.

1. Linearity.
2. Additivity.
4. Monotonicity.
4. Triangle inequality.
:::

:::{.theorem #b name="Bounded convergence theorem"}
Suppose that $\{f_n\}$ is a sequence of measurable functions that are all bounded by $M$, are supported on a set $E$ of finite measure, and $f_n(x)\to f(x)$ a.e. $x$ as $n\to\infty$. Then $f$ is measurable, bounded ,supported on $E$ for a.e. $x$, and
$$
\int|f_n-f|\to 0 \text{ as } n\to\infty.
$$
Consequently,
$$
\int f_n\to \int f  \text{ as } n\to\infty.
$$
<details>
<summary>*Proof.*</summary>
The proof is a reprise of the argument in Lemma \@ref(lem:l). Given $\epsilon>0$, we may find, by Egorov' theorem,
$$
\begin{aligned}
\int|f_n-f| &\le \int_{A_\epsilon}|f_n-f|+\int_{E-A_\epsilon}|f_n-f|\\
&\le m(E)\epsilon+2M\epsilon.
\end{aligned}
$$
for all large $n$.
</details>
:::

### Return to Riemann integrable functions

:::{.theorem}
Suppose $f$ os Riemann integrable on the closed interval $[a,b]$. Then $f$ is measurable, and
$$
\cal \int_{[a,b]}^Rf(x)\ dx=\int_{[a,b]}^Lf(x)\ dx.
$$
<details>
<summary>*Proof.*</summary>
By definition of Riemann integrability, $f$ is bounded, say $|f(x)|\le M$, and we may construct two consequences of step functions $\{\varphi_k\}$ and $\{\psi_k\}$ that satisfy the following properties: $|\varphi_k(x)\le M|$ and $|\psi_k(x)\le M|$ for all $x\in[a,b]$ and $k\ge 1$,
$$
\varphi_1(x)\le \varphi_2(x) \le \cdots\le f\le\cdots\le \psi_2(x)\le \psi_1,
$$
and
$$
\lim_{k\to\infty}\cal \int_{[a,b]}^R\varphi_k(x)\ dx=\lim_{k\to\infty}\cal \int_{[a,b]}^R\psi_k(x)\ dx=\cal \int_{[a,b]}^Rf(x)\ dx.
$$
Notice that
$$
\int_{[a,b]}^\mathcal{R}\varphi_k(x)\ dx=\int_{[a,b]}^\mathcal{L}\varphi_k(x)\ dx \text{ and }\cal \int_{[a,b]}^R\psi_k(x)\ dx=\cal \int_{[a,b]}^L\psi_k(x)\ dx.
$$
Consider Theorem \@ref(thm:b) (Bounded convergence theorem) and you will complete the proof.
</details>
:::

### Stage three: non-negative functions

In the case of such a function $f$ we define its **Lebesgue integral** by
$$
\int f =\sup_g\int g.
$$

:::{.proposition}
The integral of non-negative measurable functions enjoys the following properties:

1. Linearity.
2. Additivity.
3. Monotonicity.
4. If $g$ is integrable and $0\le f\le g$, then $f$ is integrable.
5. If $f$ is integrable, then $f(x)<\infty$ for a.e. $x$.
6. If $\int f=0$, then $f(x)=0$ for a.e. $x$.
<details>
<summary>*Proof.*</summary>
We just prove the first assertion. Let $\varphi$, $\psi$ and $\eta$ be non-negative functions bounded and supported on sets of finite measure, where $\varphi\le f$, $\psi\le g$ and $\eta\le f+g$, then $\varphi+\psi\le f+g$. Consequently,
$$
\int f+ \int g\le \int (f+g).
$$
On the other hand, if we define $\eta_1=\min(f(x),\eta(x))$ and $\eta_2=\eta-\eta_1$, then
$$
\int \eta=\int(\eta_1+\eta_2)=\int \eta_1+\int \eta_2\le\int f+ \int g,
$$
which means that
$$
\int (f+g)\le \int f+ \int g.
$$
</details>
:::

:::{.lemma #fatou name="Fatou"}
Suppose $\{f_n\}$ is a sequence of measurable functions with $f_n\ge 0$. If $\lim_{n\to\infty}f_n(x)=f(x)$ for a.e. $x$, then
$$
\int f\leq \liminf_{n\to\infty}\int f_n.
$$
<details>
<summary>*Proof.*</summary>
Suppose $0\le g\le f$, where $g$ is bounded and supported on a set $E$ of finite measure. If we set $g_n(x)=\min(g(x),f_n(x))$, then $g_n\to g$ a.e. as $n\to \infty$. By Theorem \@ref(thm:b) (Bounded convergence theorem) we have
$$
\int g_n\to \int g.
$$
Since $g_n\le f_n$, we have $\int f_n\le \int g_n$, so that
$$
\int g\le \liminf_{n\to\infty}\int f_n.
$$
Taking the supremum over all $g$ yields the desired inequality.
</details>
:::

:::{.corollary}
Suppose $f$ is a non-negative measurable function, and $\{f_n\}$ a sequence of non-negative measurable functions with $f_n(x) \le f(x)$ and $f_n(x)\to f(x)$ for a.e. $x$. Then
$$
\lim_{n\to\infty}\int f_n=\int f.
$$
:::

:::{.corollary #m name="Monotone convergence theorem"}
Suppose $\{f_n\}$ a sequence of non-negative measurable functions with $f_n(x) \nearrow f(x)$. Then
$$
\lim_{n\to\infty}\int f_n=\int f.
$$
:::

:::{.corollary #sm}
Consider a series $\sum_{k=1}^{\infty}a_k(x)$, where $a_k(x)\ge 0$ is measurable for every $k\ge 1$. Then
$$
\int \sum_{k=1}^{\infty}a_k(x)\ dx =\sum_{k=1}^{\infty}\int a_k(x)\ dx.
$$
:::

### General form

In this case, we define the **Lebesgue integral** of $f$ by
$$
\int f =\int f^+-\int f^-.
$$

:::{.proposition}
The integral of Lebesgue integrable functions is linear, additive, monotonic, and satisfies the triangle inequality.
:::

:::{.proposition #uc}
Suppose $f$ is integral on $\mathbb{R}^d$. Then for every $\epsilon>0$:

1. There exists a set of finite measure $B$ (a ball, for example) such that
$$
\int_{B^c}|f|<\epsilon.
$$
2. There is a $\delta>0$ such that
$$
\int_E|f|<\epsilon\quad \text{ whenever }m(E)<\delta.
$$
<details>
<summary>*Proof.*</summary>
Assume that $f\ge 0$: 1. $B_N=(-N,N)$; 2. $E_N=\{x:f(x)\le N\}$.
</details>
:::

:::{.theorem #dc name="Dominated convergence theorem"}
Suppose $\{f_n\}$ is a sequence of measurable functions such that $f_n\to f$ a.e. $x$ as $n$ tends to infinity. If $f_n(x)\le g(x)$, where $g$ is integrable, then
$$
\int |f_n-f|\to 0 \quad \text{ as }n\to \infty,
$$
and consequently
$$
\int f_n \to \int f.
$$
<details>
<summary>*Proof.*</summary>
For each $N\ge 0$ let $E_N=\{x:|x|\le N, g(x)\le N\}$.
$$
\begin{aligned}
\int|f_n-f|&=\int_{E_N}|f_n-f|+\int_{E_N^c}|f_n-f|\\
&\le \int_{E_N}|f_n-f|+2\int_{E_N^c}g\\
&\le \epsilon +2\epsilon
\end{aligned}
$$
for all large $n$. This prove the theorem.
</details>
:::

### Complex-valued functions

The collection of all complex-valued integrable functions on a measurable subset $E\subset \mathbb{R}^d$ forms a vector space over $\mathbb{C}$.

## The space $L^1$ of integrable functions
For any integrable function $f$ on $\mathbb{R}^d$ we define the $L^1$-norm of $f$,
$$
\|f\|=\|f\|_{L^1}=\|f\|_{L^1(\mathbb{R}^d)}=\int_{\mathbb{R}^d}|f|.
$$

:::{.proposition}
Suppose $f$ and $g$ are two functions in $L^1(\mathbb{R}^d)$.

1. $\|af\|=|a|\|f\|$ for all $a\in\mathbb{C}$.
2. $\|f+g\|\le \|f\|+\|g\|$.
3. $\|f\|=0$ iff $f=0$ a.e.
4. $d(f,g)=\|f-g\|$ defines a metric on $L^1(\mathbb{R}^d)$.
:::

:::{.theorem #rf name="Riesz-Fischer"}
The vector space $L^1$ is complete in its metric.
:::

:::{.corollary}
If $\{f_n\}_{n=1}^\infty$ converges to $f$ in $L^1$, the nthere exists a subsequence $\{f_{n_k}\}_{k=1}^\infty$ such that
$$
f_{n_k}(x)\to f(x)\quad a.e. x.
$$
:::

We say that a family $\cal G$ of integrable functions is **dense** in $L^1$ if for ant $f\in L^1$ and $\epsilon>0$, there exists $g\in\cal G$ so that $\|f-g\|<\epsilon$.

:::{.theorem #d}
The following families of functions are dense in $L^1(\mathbb{R}^d)$:

1. The simple functions.
2. The step functions.
3. The continuous functions of compact support.
:::


### Invariance properties

### Translations and continuity

:::{.proposition}
Suppose $f\in L^1(\mathbb{R}^d)$. Then
$$
\|f_h-f\|\to 0\quad \text{ as }h\to 0.
$$
<details>
<summary>*Proof.*</summary>
By Theorem \@ref(thm:d), find a continuous function with compact support to approximate $f$.
</details>
:::

## Fubini's theorem

## A Fourier inversion formula

## Exercise

## Problem
:::
